### ISSUE TITLE
运行时出现问题

### ISSUE THREAD

**Issue by xiaocaof** [HorizonRDK/line_follower#7]
在运行时 第一无法打开model文件 getmodel（）函数返回值 model_manage 一直为0 
                第二 对于usb摄像头 发布的640*480图像格式 好像无法订阅 显示Util left: 0 and right: 959, should be in [0, 640)

**Comment by WuChao-2024** [comment]
你好，getmodel读取文件的错误，一般要确认：模型文件名称和路径是否正确，尤其是相对路径描述时的合法性，模型文件是否合法且存在，程序是否有权限读取这个文件（root权限）。
USB摄像头发布的数据一般是直接从v4l2拿到的MJPEG数据，不是OpenCV读到的BGR8格式，请使用codec节点将MJPEG转为nv12(推荐)或者BGR8使用
